/**
 * Bake the harness brand marks into src/lib/harness-logos.ts.
 *
 * simple-icons is a devDependency and the paths are committed, the same deal
 * as the Nerd Font subset: nothing is fetched at runtime, and the CSP forbids
 * loading an icon from a CDN anyway.
 *
 * Only agents whose mark is unambiguously THEIRS are listed. simple-icons has
 * a "Pi", an "AMP" and a "Hermes", none of which are herdr's pi, amp or
 * hermes — wearing another company's logo is worse than wearing none, so
 * those keep the generic glyph. OpenAI (codex) and xAI (grok) have no entry
 * at all; simple-icons dropped them at the owners' request, and hand-copying
 * the mark back in would be the same act with extra steps.
 *
 *   bun run scripts/build-harness-logos.ts
 */
import { writeFileSync } from 'node:fs';
import * as icons from 'simple-icons';

/** herdr's agent name → the simple-icons title that really is that agent. */
const MARKS: Record<string, string> = {
	claude: 'Claude',
	gemini: 'Google Gemini',
	copilot: 'GitHub Copilot',
	cursor: 'Cursor',
	opencode: 'OpenCode',
	qwen: 'QWen',
	kimi: 'Kimi',
	cline: 'Cline'
};

type Icon = { title: string; path: string; hex: string; source: string; license?: unknown };
const byTitle = new Map<string, Icon>(
	Object.values(icons as Record<string, Icon>)
		.filter((i) => i && typeof i.title === 'string')
		.map((i) => [i.title, i])
);

const entries: string[] = [];
const credits: string[] = [];
for (const [agent, title] of Object.entries(MARKS)) {
	const icon = byTitle.get(title);
	if (!icon) throw new Error(`simple-icons has no "${title}" — check the title, do not guess one`);
	entries.push(`\t${agent}: '${icon.path}'`);
	credits.push(`| ${agent} | ${icon.title} | ${icon.source} |`);
}

writeFileSync(
	'src/lib/harness-logos.ts',
	`// GENERATED by scripts/build-harness-logos.ts — do not edit by hand.
// Brand marks from simple-icons (CC0-1.0); each remains its owner's trademark
// and is used here only to identify that tool. See static/LOGOS.md.

/** A 24x24 viewBox path per agent, single colour, filled with currentColor. */
export const HARNESS_LOGO: Record<string, string> = {
${entries.join(',\n')}
};
`
);

writeFileSync(
	'static/LOGOS.md',
	`# Harness marks

Baked into \`src/lib/harness-logos.ts\` by \`scripts/build-harness-logos.ts\`
from [simple-icons](https://simpleicons.org) (icon data CC0-1.0).

Each mark remains the trademark of its owner and is used here only to identify
that tool inside bordr. No endorsement is implied.

| agent | mark | source |
| --- | --- | --- |
${credits.join('\n')}

Agents with no mark here (codex, grok, pi, omp, agy, and the rest) fall back to
a Nerd Font glyph. simple-icons carries no OpenAI or xAI icon — both were
removed at the owners' request — and its "Pi", "AMP" and "Hermes" are different
products entirely.
`
);

console.log(`wrote ${entries.length} marks`);
